spring:
   datasource:
      # \u4F7F\u7528\u963F\u91CC\u7684Druid\u8FDE\u63A5\u6C60
  #    type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      # \u586B\u5199\u4F60\u6570\u636E\u5E93\u7684url\u3001\u767B\u5F55\u540D\u3001\u5BC6\u7801\u548C\u6570\u636E\u5E93\u540D
      url: jdbc:mysql://10.1.117.71:3308/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
   redis:
      host: 10.1.117.71
      port: 6001
      timeout: 1000
      database: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ebupt.entity

logging:
  level:
   root: info
  file: E://logs/hight.log
